### ISSUE TITLE
Failed to deploy a pod to windows

### ISSUE THREAD

**Issue by yanrunming** [Siemens-Healthineers/K2s#738]
According to the official building guide (https://siemens-healthineers.github.io/K2s/latest/user-guide/building-container-image/#building-a-windows-container-image), I built a container image and failed to deploy it to the win10 node.

My steps:
1. Create a simple console project (dotnet framework 4.7.2) for testing
```
        static void Main(string[] args)
        {
            Console.WriteLine("test1");
            Console.ReadKey();
        }
```
2. Add the docker file
![Screenshot 2024-09-12 155716](https://github.com/user-attachments/assets/93551251-713b-49bc-a0cc-4c4c2c1d6645)
```dockerfile
# tag 6, Use the Microsoft Windows Server Core image with .NET Framework 4.7.2
FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019
# tag 5
# FROM mcr.microsoft.com/windows/servercore:ltsc2019
# tag 4
# FROM mcr.microsoft.com/windows/nanoserver:ltsc2019

# Set up environment variables
ENV DOTNET_RUNNING_IN_CONTAINER=true

# Set the working directory
WORKDIR /app

# Copy the application files to the container
COPY bin/Debug/ .

# Specify the command to run your application
CMD ["ConsoleApp1.exe"]
```
3. Build the container image
```cmd
c:\k2s\k2s image build --input-folder Z:\test\docker\ConsoleApp1\ConsoleApp1 --windows --image-name local/consoleapp1 --image-tag 6 -o
```
![Screenshot 2024-09-12 160056](https://github.com/user-attachments/assets/fbf67593-4b77-42c1-8b3b-cc3339064969)
4. Apply the pod
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consoleapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consoleapp1
  template:
    metadata:
      labels:
        app: consoleapp1
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: "OS"
          operator: "Equal"
          value: "Windows"
          effect: "NoSchedule"
      containers:
      - name: consoleapp1
        image: docker.io/local/consoleapp1:6
```
5. But the pods failed to run
![Screenshot 2024-09-12 160524](https://github.com/user-attachments/assets/626ec795-7ee6-4a64-8d99-f248f439af07)
My environments
![Screenshot 2024-09-12 160819](https://github.com/user-attachments/assets/1c0a0753-b2e5-4a81-9b9b-a9fe55479d80)

Thanks!
